### ISSUE TITLE
Install vulnerable API apps

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/hacking-apis#5]
## Tasks
- [x] Install OWASP crAPI.
- [x] Install OWASP DevSlop Pixi.
- [x] Install OWASP Juice Shop.
- [x] Install Damn Vulnerable GraphQL.

**Comment by jelaiw** [comment]
```sh
$ ./run.sh 
DVGA Server Version: 2.1.2 Running...
```

vscode Docker extension does not know how to run this, so wrote a small shell script with the necessary magic incantation.
